apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-prod-plant-project
  namespace: argocd
spec:
  description: ArgoCD prod Plant Project
  sourceRepos:
  - https://github.com/Devops-IAC-Org/k8s-practice
  destinations:
  - server: https://kubernetes.default.svc
    namespace: prod-team-a
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'
