apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, a1427aa1-3f45-4ebb-ad83-8c795e1c9c83, role:admin
    g, 15f1b4de-b458-4c21-abd5-6481829b8adf, role:readonly
  scopes: "[groups]"
