apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-plant-app-prod
  namespace: argocd
spec:
  project: argocd-prod-plant-project
  source:
    repoURL: https://github.com/Devops-IAC-Org/k8s-practice
    targetRevision: v1.0.1
    path: apps/plant-app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-team-a
  syncPolicy: {}
